-- 混沌卷累计记账：可从橙桶拆出深绿分色；旧装无法回算，默认 0。
ALTER TABLE `inventoryequipment`
    ADD COLUMN chaosStr SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计STR(可负)' AFTER reforgeLock,
    ADD COLUMN chaosDex SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计DEX' AFTER chaosStr,
    ADD COLUMN chaosInt SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计INT' AFTER chaosDex,
    ADD COLUMN chaosLuk SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计LUK' AFTER chaosInt,
    ADD COLUMN chaosHp SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计HP' AFTER chaosLuk,
    ADD COLUMN chaosMp SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计MP' AFTER chaosHp,
    ADD COLUMN chaosWatk SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计物攻' AFTER chaosMp,
    ADD COLUMN chaosMatk SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计魔攻' AFTER chaosWatk,
    ADD COLUMN chaosWdef SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计物防' AFTER chaosMatk,
    ADD COLUMN chaosMdef SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计魔防' AFTER chaosWdef,
    ADD COLUMN chaosAcc SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计命中' AFTER chaosMdef,
    ADD COLUMN chaosAvoid SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计回避' AFTER chaosAcc,
    ADD COLUMN chaosSpeed SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计移速' AFTER chaosAvoid,
    ADD COLUMN chaosJump SMALLINT NOT NULL DEFAULT 0 COMMENT '混沌累计跳跃' AFTER chaosSpeed;
