-- 战力 / 装备评分排行榜缓存

CREATE TABLE IF NOT EXISTS `ranking_combat_power` (
    `character_id` INT NOT NULL,
    `world` INT NOT NULL DEFAULT 0,
    `name` VARCHAR(13) NOT NULL,
    `job` INT NOT NULL DEFAULT 0,
    `job_niche` INT NOT NULL DEFAULT 0 COMMENT 'job DIV 100，与等级榜分职一致',
    `level` INT NOT NULL DEFAULT 1,
    `combat_power` BIGINT NOT NULL DEFAULT 0,
    `base_damage` INT NOT NULL DEFAULT 0,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`character_id`),
    KEY `idx_rcp_power` (`combat_power` DESC),
    KEY `idx_rcp_job_power` (`job_niche`, `combat_power` DESC),
    KEY `idx_rcp_world_power` (`world`, `combat_power` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ranking_equip_score` (
    `inventory_item_id` BIGINT NOT NULL,
    `character_id` INT NOT NULL,
    `character_name` VARCHAR(13) NOT NULL,
    `world` INT NOT NULL DEFAULT 0,
    `item_id` INT NOT NULL,
    `item_name` VARCHAR(255) DEFAULT NULL,
    `position` SMALLINT NOT NULL DEFAULT 0,
    `slot_category` INT NOT NULL DEFAULT 0 COMMENT '部位分类，见 EquipRankCategory',
    `equipped` TINYINT NOT NULL DEFAULT 0,
    `score` BIGINT NOT NULL DEFAULT 0,
    `str` SMALLINT NOT NULL DEFAULT 0,
    `dex` SMALLINT NOT NULL DEFAULT 0,
    `inte` SMALLINT NOT NULL DEFAULT 0,
    `luk` SMALLINT NOT NULL DEFAULT 0,
    `hp` SMALLINT NOT NULL DEFAULT 0,
    `mp` SMALLINT NOT NULL DEFAULT 0,
    `watk` SMALLINT NOT NULL DEFAULT 0,
    `matk` SMALLINT NOT NULL DEFAULT 0,
    `wdef` SMALLINT NOT NULL DEFAULT 0,
    `mdef` SMALLINT NOT NULL DEFAULT 0,
    `acc` SMALLINT NOT NULL DEFAULT 0,
    `avoid` SMALLINT NOT NULL DEFAULT 0,
    `hands` SMALLINT NOT NULL DEFAULT 0,
    `speed` SMALLINT NOT NULL DEFAULT 0,
    `jump` SMALLINT NOT NULL DEFAULT 0,
    `upgradeslots` TINYINT NOT NULL DEFAULT 0,
    `level` TINYINT NOT NULL DEFAULT 0,
    `vicious` SMALLINT NOT NULL DEFAULT 0,
    `itemlevel` TINYINT NOT NULL DEFAULT 0,
    `itemexp` INT NOT NULL DEFAULT 0,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`inventory_item_id`),
    KEY `idx_res_score` (`score` DESC),
    KEY `idx_res_slot_score` (`slot_category`, `score` DESC),
    KEY `idx_res_character` (`character_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
