/*
    This file is part of a Maple Story Server and is redistributed under the
    licence below

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation version 3 as published by
    the Free Software Foundation. You may not use, modify or distribute
    this program under any other version of the GNU Affero General Public
    License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package org.gms.server.lamp;

/**
 * The lamps {@code !lamp} can preview. GENERATED by gen_lamp_catalog.py.
 *
 * <p>THE ORDER IS THE WIRE FORMAT. {@code !lamp 7} sends index 7 and the client looks
 * up row 7 of {@code kLamps} in {@code client/weather_lamptable.inc}, which is generated
 * from the same table in the same order. Reordering this list without rebuilding the DLL
 * previews the wrong lamp, silently.
 *
 * @see LampPackets
 */
public final class LampCatalog {

    private LampCatalog() {
    }

    /** Short name of each lamp, indexed as the client indexes them. */
    public static final String[] NAMES = {
            "waitan",
            "cbd",
            "cbdWide",
            "amoria",
            "magatia",
            "nlc",
            "henesys",
            "ludibrium",
            "kerning",
            "nightMkt",
            "xmas",
            "xmasRibbon",
            "brazier",
            "fire",
            "campfire",
            "torchBowl",
            "caveTorch",
            "candelabra",
            "wallCandle",
            "candle",
            "neon",
            "glowFlower",
            "glowBloom",
            "crystal",
            "barrelPortal",
            "barrelPortal0",
            "seaLantern11",
            "seaLantern12",
            "seaLantern13",
            "aquariumWall1",
            "aquariumWall2",
            "aquariumWall3",
            "gaslamp",
            "annualLamp",
            "annualLights",
            "annualBunting",
            "crystalPost",
            "ornatePost",
            "wingedPost",
            "floodlight",
            "paperGold",
            "paperPink",
            "vineLantern",
            "vineLampShort",
            "vineLampLong",
            "festivalPillar",
            "floorCream",
            "floorPink",
            "floorPinkSlim",
            "carriageLg",
            "carriageMd",
            "carriageSm",
            "sconceBlue",
            "sconceWhite",
            "sconceGold",
            "wallTorch",
            "wallTorchBig",
            "wallBrazier",
            "sconceCandle",
            "chandelierGold",
            "chandelierSmall",
            "chandelierHall",
            "chandelierCone",
            "hangBrazier",
            "hangCandle",
            "tripodFire",
            "tripodGreen",
            "tripodFireBig",
            "goldBowl",
            "woodTripod",
            "fireBasket",
            "crystalArch",
            "neonSign",
            "neonStar",
    };

    /** The WZ sprite each name refers to, so the listing can be checked against the art. */
    public static final String[] PATHS = {
            "Map/Obj/ShanghaiCN.img/waitan/artificiality/1",
            "Map/Obj/citySG.img/CBD/artificiality/26",
            "Map/Obj/citySG.img/CBD/artificiality/27",
            "Map/Obj/WeddingGL.img/town/light/2",
            "Map/Obj/acc8.img/magatia/acc/1",
            "Map/Obj/ThemeGL.img/Themetown/Streetlight/1",
            "Map/Obj/acc1.img/grassySoil/space/21",
            "Map/Obj/acc4.img/toyCastle/artificiality/8",
            "Map/Obj/acc2.img/metroCity/nightMarket/1",
            "Map/Obj/NightMarketTW.img/NightMarket/StreetVender4/9",
            "Map/Obj/acc3.img/christmas/acc/8",
            "Map/Obj/EventCN.img/JumpEvent/acc/8",
            "Map/Obj/acc8.img/sahelDesert/piramid/4",
            "Map/Obj/acc12.img/aran/fire/0",
            "Map/Obj/acc12.img/rienFD/pengiun/5",
            "Map/Obj/guide.img/milepost/eurel/0",
            "Map/Obj/ShamanBT.img/koCave/object/28",
            "Map/Obj/halloween.img/inside/common/27",
            "Map/Obj/halloweenGL.img/halloween/room2/wallcandle2",
            "Map/Obj/ShaolinCN.img/house15/base/11",
            "Map/Obj/acc2.img/metroCity/artificiality/20",
            "Map/Obj/acc6.img/minar/nature1/28",
            "Map/Obj/arcana.img/lightForest/acc/0",
            "Map/Obj/acc9.img/nautilus/ship/3",
            "Map/Obj/acc9.img/nautilusPort/portal/1",
            "Map/Obj/acc9.img/nautilusPort/portal/0",
            "Map/Obj/acc5.img/aquaRoad/acc2/11",
            "Map/Obj/acc5.img/aquaRoad/acc2/12",
            "Map/Obj/acc5.img/aquaRoad/acc2/13",
            "Map/Obj/houseAR.img/house0/acc/1",
            "Map/Obj/houseAR.img/house0/acc/2",
            "Map/Obj/houseAR.img/house0/acc/3",
            "Map/Obj/MapleMoonLamp2.img/street/gaslamp/0",
            "Map/Obj/MapleMoonLamp2.img/street/annual/0",
            "Map/Obj/MapleMoonLamp2.img/street/annual/1",
            "Map/Obj/MapleMoonLamp2.img/street/annual/2",
            "Map/Obj/MapleMoonLamp2.img/street/crystal/0",
            "Map/Obj/MapleMoonLamp2.img/street/ornate/0",
            "Map/Obj/MapleMoonLamp2.img/street/winged/0",
            "Map/Obj/MapleMoonLamp2.img/street/flood/0",
            "Map/Obj/MapleMoonLamp2.img/street/paper/0",
            "Map/Obj/MapleMoonLamp2.img/street/paper/1",
            "Map/Obj/MapleMoonLamp2.img/street/vine/0",
            "Map/Obj/MapleMoonLamp2.img/street/vine/1",
            "Map/Obj/MapleMoonLamp2.img/street/vine/2",
            "Map/Obj/MapleMoonLamp2.img/street/pillar/0",
            "Map/Obj/MapleMoonLamp2.img/floor/shade/0",
            "Map/Obj/MapleMoonLamp2.img/floor/shade/1",
            "Map/Obj/MapleMoonLamp2.img/floor/shade/2",
            "Map/Obj/MapleMoonLamp2.img/wall/carriage/0",
            "Map/Obj/MapleMoonLamp2.img/wall/carriage/1",
            "Map/Obj/MapleMoonLamp2.img/wall/carriage/2",
            "Map/Obj/MapleMoonLamp2.img/wall/crystal/0",
            "Map/Obj/MapleMoonLamp2.img/wall/crystal/1",
            "Map/Obj/MapleMoonLamp2.img/wall/crystal/2",
            "Map/Obj/MapleMoonLamp2.img/wall/torch/0",
            "Map/Obj/MapleMoonLamp2.img/wall/torch/1",
            "Map/Obj/MapleMoonLamp2.img/wall/torch/2",
            "Map/Obj/MapleMoonLamp2.img/wall/candle/0",
            "Map/Obj/MapleMoonLamp2.img/hang/chandelier/0",
            "Map/Obj/MapleMoonLamp2.img/hang/chandelier/1",
            "Map/Obj/MapleMoonLamp2.img/hang/chandelier/2",
            "Map/Obj/MapleMoonLamp2.img/hang/chandelier/3",
            "Map/Obj/MapleMoonLamp2.img/hang/lantern/0",
            "Map/Obj/MapleMoonLamp2.img/hang/candle/0",
            "Map/Obj/MapleMoonLamp2.img/fire/brazier/0",
            "Map/Obj/MapleMoonLamp2.img/fire/brazier/1",
            "Map/Obj/MapleMoonLamp2.img/fire/brazier/2",
            "Map/Obj/MapleMoonLamp2.img/fire/bowl/0",
            "Map/Obj/MapleMoonLamp2.img/fire/tripod/0",
            "Map/Obj/MapleMoonLamp2.img/fire/basket/0",
            "Map/Obj/MapleMoonLamp2.img/fire/arch/0",
            "Map/Obj/MapleMoonLamp2.img/neon/sign/0",
            "Map/Obj/MapleMoonLamp2.img/neon/star/0",
    };

    /** How many separate lights the sprite carries. Henesys' post has three globes. */
    public static final int[] LIGHTS = {
            1, 1, 1, 1, 2, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 4, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1,
    };

    /** Where the lamp already stands in stock data, purely so the listing is useful. */
    public static final String[] WHERE = {
            "unplaced",
            "8 placement(s)",
            "10 placement(s)",
            "Amoria",
            "Magatia",
            "New Leaf City",
            "Henesys",
            "Ludibrium",
            "Kerning City",
            "5 placement(s)",
            "1 placement(s)",
            "1 placement(s)",
            "43 placement(s)",
            "3 placement(s)",
            "Amherst",
            "3 placement(s)",
            "unplaced",
            "18 placement(s)",
            "8 placement(s)",
            "unplaced",
            "1 placement(s)",
            "2 placement(s)",
            "1 placement(s)",
            "Nautilus Harbor",
            "Nautilus Harbor",
            "2 placement(s)",
            "Aqua Road",
            "Aqua Road",
            "Aqua Road",
            "Aquarium",
            "Aquarium",
            "Aquarium",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
            "unplaced",
    };

    static {
        // All four arrays are indexed by the byte sent over LP_LampPreview. Failing on
        // startup turns a generator/merge mismatch into an actionable error instead of
        // a preview of the wrong sprite.
        if (NAMES.length != PATHS.length || NAMES.length != LIGHTS.length || NAMES.length != WHERE.length) {
            throw new IllegalStateException("Lamp catalog arrays are not index-aligned");
        }
        if (NAMES.length > 256) {
            throw new IllegalStateException("Lamp catalog no longer fits the one-byte preview id");
        }
    }

    public static int size() {
        return NAMES.length;
    }

    public static boolean isValid(int id) {
        return id >= 0 && id < NAMES.length;
    }
}
